### ISSUE TITLE
The sdiff statement doesn't work.

### ISSUE THREAD

**Issue by myfirstnameispaul** [roycewilliams/iana-whois-conf#1]
This is all I get when I run the recommended `sdiff` statement. Since I am not familiar with `sdiff`, I ended up just using Excel to keep the otherwise lost TLDs.

```
$ sdiff -o whois.conf.merged whois.conf.old whois.conf
\.ac$ whois.nic.ac                                            | \.abbott$ whois.afilias-srs.net
                                                              > \.abogado$ whois-dub.mm-registry.com
%h
ed:     Edit then use both versions, each decorated with a header.
eb:     Edit then use both versions.
el or e1:       Edit then use the left version.
er or e2:       Edit then use the right version.
e:      Discard both versions then edit a new one.
l or 1: Use the left version.
r or 2: Use the right version.
s:      Silently include common lines.
v:      Verbosely include common lines.
q:      Quit.
%
```

**Comment by roycewilliams** [comment]
It was programmatically tricky to automate merging the two without human judgment, so I punted. :)  sdiff's -o option is interactive; you have to tell it what you want to do; either take the left side (l or 1), take the right side (r or 2), open all of the lines for manual merging (eb), etc.  

I will make the intent more obvious in the output and comments.

**Comment by myfirstnameispaul** [comment]
The reason I opted not to use `sdiff` is that it looked like I was going to go through the entire list, line by line. In retrospect, the StackExchange edit revision comparison tool is probably the fastest way to identify missing TLDs.

**Comment by roycewilliams** [comment]
FWIW, I've just refreshed this quite a bit - spurred by a need to generate a jwhois-compatible list.

There are now `.baseline` files that should give people some better options for detecting changes. I've also explicitly included the baseline files in the repo as a starting point.
