### ISSUE TITLE
.th whois server should be whois.thnic.net

### ISSUE THREAD

**Issue by net1** [roycewilliams/iana-whois-conf#2]
\\.th$ whois.thnic.net

**Comment by roycewilliams** [comment]
If so, IANA's published server is out of date:
```
$ lynx -dump --nolist 'https://www.iana.org/domains/root/db/th.html' | grep WHOIS
   WHOIS Server: whois.thains.co.th
```
Tracking WHOIS servers beyond what IANA themselves publish is out of scope for this project, unfortunately - not enough cycles to vet candidate changes (especially considering that the IANA reference is supposed to be authoritative).

In other words, the purpose of this project is to track what _IANA_ says is true. :)
